### ISSUE TITLE
Italicization (or lack thereof) and xml:lang

### ISSUE THREAD

**Issue by weijia-cheng** [jsluke/aldous-huxley_crome-yellow#2]
Some words that are marked with italics and xml:lang that should probably not be, per [8.2.9.1](https://standardebooks.org/manual/1.5.0/8-typography#8.2.9.1):

"élan vital" in chapter 5
"seicento" in chapter 7
"putti" in chapter 7
"palais de danse" in chapter 10
"trompe-l’oeil" in chapter 12
"lusus naturae" in chapter 13

You'd be surprised by how many seemingly non-English words and phrases are considered perfectly fine English by M-W. As a general rule of thumb it's a good precaution to check any short word or phrase in M-W, especially if it's anything you're even vaguely familiar with.

---

Conversely I see that there are many foreign-language verses/poems that are not marked with xml:lang and italicized per [8.2.9.6](https://standardebooks.org/manual/1.5.0/8-typography#8.2.9.6). I see some in chapter 17 and chapter 20. I also see in chapter 17 the sentence "Trente moutons pour un baiser." outside of a poem that is not italicized. I see that it's not italicized in the scans but as far as I understand our manual supersedes that.

---

There are a few uses of `<em>` that I'm not entirely sure are correct. `<em>` should indicate emphasized speech or at least something that should be read in a different tone than the surrounding words. I see you have a "Ferdinando goes `<em>crescendo</em>`" in chapter 13, but it might be that the word was italicized in the original scan because it was being treated as an Italian word at the time? Similarly with `<em>louche</em>` in chapter 17--I'd leave it up to you to decide on the context whether these are actually emphasized or whether they were just being treated as foreign-language words at the time. In chapter 20 I see you have `<em>windtreibend</em>` but that definitely isn't an English word per M-W.

---

In chapter 1 I see the name "Stone" is being spelled out as "S-T-O-N-E"; the individual letters should be italicized as graphemes per [8.2.8.1](https://standardebooks.org/manual/1.5.0/8-typography#8.2.8.1).

---

I see some Caravaggio painting titles like "Call of Matthew" are set in quotes in chapter 12, but these (and other painting titles) should be italicized per [8.2.11.2](https://standardebooks.org/manual/1.5.0/8-typography#8.2.11.2). The type would be `se:name.visual-art-painting`.

**Comment by jsluke** [comment]
Thanks! I have addressed these issues with these commits:
https://github.com/jsluke/aldous-huxley_crome-yellow/commit/1c069c5b3b074f76b07b24f84caf441c5b1eed1f
https://github.com/jsluke/aldous-huxley_crome-yellow/commit/954fd7659e80f3e9da2798d0791d4efd7f4dfd64
https://github.com/jsluke/aldous-huxley_crome-yellow/commit/41688ea278e6e82146467b6576beea9076d0a54e
https://github.com/jsluke/aldous-huxley_crome-yellow/commit/91cb3e75bb9756a78198f125cb5375cd4ce23b0b

Let me know if this looks good to you. Later I will do a more thorough pass looking for non-English text that hasn't been annotated with xml:lang

**Comment by weijia-cheng** [comment]
Thanks, these changes look good!

**Comment by weijia-cheng** [comment]
I think we just need to go back and add block-level xml:lang tags to the poems and verses now.

**Comment by jsluke** [comment]
Good call, I had missed that in your comment. Added them in this commit:
https://github.com/jsluke/aldous-huxley_crome-yellow/commit/7eeefabf3cc85401cf660923bc401deb8919dc13

**Comment by weijia-cheng** [comment]
Great! We should give the non-English poems block-level italicization by adding the CSS shown in [8.2.9.6](https://standardebooks.org/manual/1.5.0/8-typography#8.2.9.6) as well.

**Comment by jsluke** [comment]
Got it, added in this commit:
https://github.com/jsluke/aldous-huxley_crome-yellow/commit/3c126264740bb5f2dc718bebdc969779c6bb3584

**Comment by weijia-cheng** [comment]
Looks good!
