### ISSUE TITLE
Revert bacab980c9a4ecdfbedce94926b8d2734b6ed142

### ISSUE THREAD

**Issue by weijia-cheng** [jsluke/aldous-huxley_crome-yellow#3]
I see what you're doing here, but it's not an uncommon style for prose from that time period to put interjections! like this in the middle of a sentence instead of starting a new sentence. As far as I know there's no rule the manual that disallows this, and this is perfectly acceptable style.

**Comment by jsluke** [comment]
Sounds good, I was unfamiliar with that style. Revert commit here:
https://github.com/jsluke/aldous-huxley_crome-yellow/commit/a3ceeb0140cf1d54f301b8d9a62ac7b1004b2539
