### ISSUE TITLE
Add [Editorial] to latest modernize spelling commit

### ISSUE THREAD

**Issue by weijia-cheng** [jsluke/aldous-huxley_crome-yellow#8]
https://github.com/jsluke/aldous-huxley_crome-yellow/commit/b7b134acbc1f5118668e0af16f061a0988a42302#commitcomment-50061063

**Comment by jsluke** [comment]
Thanks, got the commit renamed now:
https://github.com/jsluke/aldous-huxley_crome-yellow/commit/d2ed64b3cdd41d813f81a80913716817db7a5633

**Comment by weijia-cheng** [comment]
:+1:
